require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec
inherit_from: .rubocop_todo.yml

Layout/LineLength:
  Max: 150
  Exclude:
    - 'db/migrate/20230222134724_create_preferences.rb'

Metrics/ClassLength:
  Max: 125
  Exclude:
    - 'app/models/conversation.rb'
    - 'app/models/contact.rb'
    - 'app/mailers/conversation_reply_mailer.rb'
    - 'app/models/message.rb'
    - 'app/builders/messages/facebook/message_builder.rb'
    - 'app/controllers/api/v1/accounts/contacts_controller.rb'
    - 'app/controllers/api/v1/conversation_messages_controller.rb'
    - 'app/listeners/action_cable_listener.rb'
    - 'app/models/conversation.rb'
RSpec/ExampleLength:
  Max: 25
Style/Documentation:
  Enabled: false
Style/ExponentialNotation:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Style/SymbolArray:
  Enabled: false
Style/OpenStructUse:
  Enabled: false
Style/OptionalBooleanParameter:
  Exclude:
    - 'app/services/email_templates/db_resolver_service.rb'
    - 'app/dispatchers/dispatcher.rb'
Style/GlobalVars:
  Exclude:
    - 'config/initializers/01_redis.rb'
    - 'config/initializers/rack_attack.rb'
    - 'lib/redis/alfred.rb'
    - 'lib/global_config.rb'
Style/ClassVars:
  Exclude:
    - 'app/services/email_templates/db_resolver_service.rb'
Lint/MissingSuper:
  Exclude:
    - 'app/drops/base_drop.rb'
Lint/SymbolConversion:
  Enabled: false
Lint/EmptyBlock:
  Exclude:
    - 'app/views/api/v1/accounts/conversations/toggle_status.json.jbuilder'
Lint/OrAssignmentToConstant:
  Exclude:
    - 'lib/redis/config.rb'
Metrics/BlockLength:
  Exclude:
    - spec/**/*
    - '**/routes.rb'
    - 'config/environments/*'
    - db/schema.rb
Metrics/ModuleLength:
  Exclude:
    - lib/seeders/message_seeder.rb
Rails/ApplicationController:
  Exclude:
    - 'app/controllers/api/v1/widget/messages_controller.rb'
    - 'app/controllers/dashboard_controller.rb'
    - 'app/controllers/widget_tests_controller.rb'
    - 'app/controllers/widgets_controller.rb'
    - 'app/controllers/platform_controller.rb'
    - 'app/controllers/public_controller.rb'
    - 'app/controllers/survey/responses_controller.rb'
Rails/CompactBlank:
  Enabled: false
Rails/EnvironmentVariableAccess:
  Enabled: false
Rails/TimeZoneAssignment:
  Enabled: false
Rails/RedundantPresenceValidationOnBelongsTo:
  Enabled: false
Style/ClassAndModuleChildren:
  EnforcedStyle: compact
  Exclude:
    - 'config/application.rb'
Style/MapToHash:
  Enabled: false
RSpec/NestedGroups:
  Enabled: true
  Max: 4
RSpec/MessageSpies:
  Enabled: false
RSpec/StubbedMock:
  Enabled: false
RSpec/FactoryBot/SyntaxMethods:
  Enabled: false
Naming/VariableNumber:
  Enabled: false
Metrics/MethodLength:
  Exclude:
    - 'db/migrate/*'
    - 'app/models/ability.rb'
    - 'app/controllers/concerns/exception_handler.rb'
Rails/CreateTableWithTimestamps:
  Exclude:
    - 'db/migrate/20170207092002_acts_as_taggable_on_migration.acts_as_taggable_on_engine.rb'
Style/GuardClause:
  Exclude:
    - 'app/builders/account_builder.rb'
    - 'app/models/attachment.rb'
    - 'app/models/message.rb'
    - 'db/migrate/*'
Metrics/AbcSize:
  Exclude:
    - 'app/controllers/concerns/auth_helper.rb'
    - 'app/controllers/api/v1/accounts/inboxes_controller.rb'
    - 'app/models/ability.rb'
    - 'app/controllers/concerns/exception_handler.rb'
    - 'db/migrate/*'
Metrics/CyclomaticComplexity:
  Max: 7
  Exclude:
    - 'db/migrate/*'
    - 'app/models/ability.rb'
Metrics/PerceivedComplexity:
  Exclude:
    - 'app/models/ability.rb'
Rails/ReversibleMigration:
  Exclude:
    - 'db/migrate/*'
Rails/BulkChangeTable:
  Exclude:
    - 'db/migrate/*'
Rails/UniqueValidationWithoutIndex:
  Exclude:
    - 'app/models/channel/twitter_profile.rb'
    - 'app/models/webhook.rb'
    - 'app/models/contact.rb'
    - 'app/models/integrations/hook.rb'
Rails/RenderInline:
  Exclude:
    - 'app/controllers/swagger_controller.rb'
Performance/CollectionLiteralInLoop:
  Exclude:
    - 'db/migrate/*'
RSpec/NamedSubject:
  Enabled: false
# we should bring this down
RSpec/MultipleMemoizedHelpers:
  Max: 12

Rails/HasManyOrHasOneDependent:
  Enabled: false

Rails/InverseOf:
  Enabled: false

Rails/NotNullColumn:
  Enabled: false

AllCops:
  NewCops: enable
  Exclude:
    - 'bin/**/*'
    - 'db/schema.rb'
    - 'public/**/*'
    - 'config/initializers/bot.rb'
    - 'vendor/**/*'
    - 'node_modules/**/*'
    - 'lib/tasks/auto_annotate_models.rake'
    - 'config/environments/**/*'
    - 'tmp/**/*'
    - 'storage/**/*'
    - 'db/migrate/*'
    - 'test/test_helper.rb'

