require:
  - rubocop-rspec
  - rubocop-rails
  - rubocop-performance
  - ./.rubocop/custom_cops

inherit_from:
  - .rubocop_todo.yml
  - ./.rubocop/.rubocop_rails.yml
  - ./.rubocop/.rubocop_rspec.yml
  - ./.rubocop/.rubocop_custom.yml

inherit_mode:
  merge:
    - Exclude

AllCops:
  TargetRubyVersion: 2.7
  NewCops: enable
  Exclude:
    - 'bin/**/*'
    - 'config/**/*'
    - 'vendor/**/*'

Bundler/OrderedGems:
  Enabled: true

Bundler/DuplicatedGem:
  Enabled: true

Layout/ClassStructure:
  Enabled: true
  AutoCorrect: false
  Categories:
    module_inclusion:
      - include
      - prepend
      - extend
    attributes:
      - attribute
      - attr_reader
      - attr_writer
      - attr_accessor
      - alias_attribute
      - delegate
      - enum
    associations:
      - belongs_to
      - has_one
      - has_many
      - has_and_belongs_to_many
    validations:
      - validates
      - validate
      - validates_with
    callbacks:
      - before_validation
      - before_save
      - before_create
      - before_destroy
      - after_initialize
      - after_create
      - after_save
      - after_destroy
      - after_commit
      - after_create_commit
      - after_update_commit
      - after_destroy_commit
      - around_create
    other_macros:
      - devise
      - serialize
      - has_paper_trail
      - audited
      - monetize
    scopes:
      - default_scope
      - scope
    controller_macros:
      - protect_from_forgery
      - respond_to
    controller_actions:
      - before_action
      - skip_before_action
    controller_rescue:
      - rescue_from
  ExpectedOrder:
    - module_inclusion
    - constants
    - attributes
    - enums
    - associations
    - validations
    - callbacks
    - scopes
    - controller_macros
    - controller_actions
    - controller_rescue
    - class_methods
    - initializer
    - public_methods
    - protected_methods
    - private_methods

Layout/EmptyLineAfterGuardClause:
  Enabled: false

Layout/EmptyLinesAroundAttributeAccessor:
  Enabled: true

Layout/EmptyLineBetweenDefs:
  AllowAdjacentOneLineDefs: true

Layout/EndAlignment:
  EnforcedStyleAlignWith: variable

Layout/LineLength:
  Max: 100
  AutoCorrect: false

Layout/SpaceAroundOperators:
  AllowForAlignment: false

Layout/SpaceAroundMethodCallOperator:
  Enabled: true

Lint/AmbiguousBlockAssociation:
  Exclude:
    - 'spec/**/*'

Lint/ElseLayout:
  Enabled: false

Lint/EmptyBlock:
  Exclude:
    - 'spec/factories/**/*'

Lint/NonLocalExitFromIterator:
  Enabled: true

Lint/RaiseException:
  Enabled: true

Lint/ShadowingOuterLocalVariable:
  Enabled: false


Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/ClassLength:
  Max: 250

Metrics/CyclomaticComplexity:
  Enabled: false
Metrics/MethodLength:
  Max: 30
Metrics/ModuleLength:
  Max: 250
  Exclude:
    - 'spec/**/*'
    -
Metrics/ParameterLists:
  Max: 4
  CountKeywordArgs: false

Naming/AccessorMethodName:
  Enabled: false

Naming/MethodParameterName:
  Enabled: false

Style/Alias:
  EnforcedStyle: prefer_alias_method

Style/ArrayCoercion:
  Enabled: false

Style/MultilineMethodSignature:
  Enabled: true

Style/BlockDelimiters:
  Exclude:
    - 'spec/**/*'
Style/ClassMethodsDefinitions:
  Enabled: true

Style/CollectionMethods:
  Enabled: true

Style/DisableCopsWithinSourceCodeDirective:
  Enabled: true

Style/Documentation:
  Enabled: false

Style/ExplicitBlockArgument:
  Enabled: false

Style/ExponentialNotation:
  Enabled: true

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

Style/IfUnlessModifier:
  Enabled: false

Style/Lambda:
  Enabled: false

Style/NegatedIf:
  Enabled: false

Style/Next:
  Enabled: false

Style/NumericPredicate:
  Enabled: false

Style/NumericLiterals:
  Exclude:
    - 'db/migrate/*'
    - 'spec/**/*'

Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    'default': '()'
    '%': '()'
    '%i': '()'
    '%I': '()'
    '%q': '()'
    '%Q': '()'
    '%r': '()'
    '%s': '()'
    '%w': '()'
    '%W': '()'
    '%x': '()'

Style/RaiseArgs:
  Enabled: false

Style/RedundantArgument:
  Enabled: false

Style/RedundantBegin:
  Enabled: true

Style/RedundantRegexpCharacterClass:
  Enabled: true

Style/RedundantRegexpEscape:
  Enabled: true

Style/SafeNavigation:
  Enabled: false

Style/SingleLineMethods:
  Enabled: true

Style/SlicingWithRange:
  Enabled: true

Style/SymbolArray:
  Enabled: false

Style/SymbolProc:
  Enabled: true

Style/UnlessLogicalOperators:
  Enabled: true
  EnforcedStyle: forbid_logical_operators




