require:
  - rubocop-rspec

RSpec/AnyInstance:
  Enabled: false

RSpec/DescribedClass:
  EnforcedStyle: explicit

RSpec/EmptyLineAfterFinalLet:
  Enabled: false

RSpec/ExampleLength:
  Max: 20

RSpec/FilePath:
  SpecSuffixOnly: true

RSpec/ImplicitExpect:
  EnforcedStyle: should

RSpec/LetSetup:
  Enabled: false

RSpec/MultipleMemoizedHelpers:
  Enabled: false

RSpec/MessageChain:
  Enabled: false

RSpec/MissingExampleGroupArgument:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/NestedGroups:
  Max: 6

RSpec/VerifiedDoubles:
  Enabled: false

RSpec/Focus:
  Enabled: true

RSpec/EmptyExampleGroup:
  Enabled: true

RSpec/EmptyLineAfterExampleGroup:
  Enabled: true

RSpec/EmptyLineAfterHook:
  Enabled: true

RSpec/EmptyLineAfterSubject:
  Enabled: true

RSpec/HookArgument:
  Enabled: true

RSpec/HooksBeforeExamples:
  Enabled: true

RSpec/IteratedExpectation:
  Enabled: true

RSpec/LetBeforeExamples:
  Enabled: true

RSpec/ReceiveCounts:
  Enabled: true

RSpec/Capybara/CurrentPathExpectation:
  Enabled: true

RSpec/FactoryBot/AttributeDefinedStatically:
  Enabled: true

RSpec/FactoryBot/CreateList:
  Enabled: true

