name: Setup

runs:
  using: composite
  steps:
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16.10.0
    - name: Install dependencies
      run: yarn install --frozen-lockfile
      shell: bash
