# Sample configuration file for Sidekiq.
# Options here can still be overridden by cmd line args.
# Place this file at config/sidekiq.yml and Sidekiq will
# pick it up automatically.
---
:verbose: false
:concurrency: 5
:timeout: 25
:max_retries: 3

# Sidekiq will run this file through ERB when reading it so you can
# even put in dynamic logic, like a host-specific queue.
# http://www.mikeperham.com/2013/11/13/advanced-sidekiq-host-specific-queues/
:queues:
  - [low, 1]
  - [scheduled_jobs, 1]
  - [webhooks, 1]
  - [bots, 1]
  - [active_storage_analysis, 1]
  - [action_mailbox_incineration, 1]
  - [active_storage_purge, 1]
  - [integrations, 2]
  - [default, 2]
  - [mailers, 2]
  - [medium, 3]
  - [events, 3]
  - [action_mailbox_routing, 3]
  - [high, 5]
  - [critical, 10]

# you can override concurrency based on environment
production:
  :concurrency: 10
staging:
  :concurrency: 5
