name: production_deployment

on:
  push:
    branches: [ deployer ]

jobs:
  deploy:
    name: Capistrano Deploy to Server
    runs-on: ubuntu-latest

    steps:
      - name: Install SSH key to Server
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.PROD_SSH_KEY }}
          name: github-actions
          known_hosts: 'random-placeholder-value-replaced-by-keyscan-below'
          config: |
            host ${{ secrets.PROD_SSH_HOST }}
              IdentityFile ~/.ssh/github-actions
              IdentitiesOnly yes
              ForwardAgent yes

      - name: Adding Known Hosts
        run: ssh-keyscan -H ${{ secrets.PROD_SSH_HOST }}

      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1.2
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically

      - name: Deploy to production
        run: |
          eval "$(ssh-agent -s)"
          ssh-add ~/.ssh/github-actions
          bundle exec cap production deploy
